# 
#' Generate igraph network
#' 
#' function to generate the igraph network from similiraty scores
#' @param similarity_output Output generated by the get_similarity_all_plots or get_similarity_all_plots_v2 function
#' @param method_clust clustering method: louvain, infomap, default to louvain
#' @return two objects
#' $igraph_network : igraph network object
#' $partition : vector of the clusters association
#' @export
#' @examples 
#' \donttest{gen_igraph_network(similarity_output=out,method_clust="louvain")}
gen_igraph_network<-function(similarity_output,method_clust="louvain"){
  set.seed(40)
  print("------- generate igraph network ----------")
  igraph_network <- graph_from_data_frame(d = similarity_output$edges,vertices=similarity_output$nodes,directed = F)
  print("------ executing clustering algorithm ------")
  df_groups<-get_groups_based_on_clustering(igraph_network,method = method_clust)
  partition<-df_groups$partition
  igraph_network<-igraph_network %>% set_vertex_attr(name="color",index = vertex_attr(igraph_network)$name,value = df_groups$final_col_vec)
  return(list(igraph_network=igraph_network,partition=partition))
}


#' Generate groups based on a clustering method
#' 
#' function to clusterize the samples using different methods. Internal function.
#' @param similarity_output Output generated by the get_similarity_all_plots or get_similarity_all_plots_v2 function
#' @param method_clust clustering method: louvain, infomap, default to louvain
#' @keywords Internal
#' @return two objects
#' $igraph_network : igraph network object
#' $partition : vector of the clusters association
get_groups_based_on_clustering<-function(igraph_network,method="louvain"){
  if(method=="louvain"){
    print("----- generating partitions-----")
    lc <- cluster_louvain(igraph_network)
    partition<-as.vector(membership(lc))
    nodes_id<-vertex_attr(igraph_network,name="name")
    # tot_n_clusters<-length(unique(partition))
    df_groups<-data.frame(nodes_id,partition)
  }else if(method=="infomap"){
    print("--- generating partitions")
    lc <- cluster_infomap(igraph_network)
    partition<-as.vector(membership(lc))
    nodes_id<-vertex_attr(igraph_network,name="name")
    # tot_n_clusters<-length(unique(partition))
    df_groups<-data.frame(nodes_id,partition)
  }else{
    stop("input clustering method not valid")
  }
  print("---- generate colors based on groups -------")
  df_groups<-get_new_colors_based_on_groups(df_groups=df_groups)
  print("Done")
  return(df_groups)
}

